### ISSUE TITLE
I can't find ConfigParser*

### ISSUE THREAD

**Issue by jfabiani** [dabodev/dabo#26]
I can't find ConfigParser*.  It is the first import of dApp.py

**Comment by EdLeafe** [comment]
It's "configparser". Are you running Python 3?

**Comment by jfabiani** [comment]
OK I see the case is different.  I'll change it???????

**Comment by EdLeafe** [comment]
No. The dabo3 branch is Python3 only.

**Comment by jfabiani** [comment]
OK Thanks for the info.
