### ISSUE TITLE
relative path and low hanging fruit

### ISSUE THREAD

**Issue by jfabiani** [dabodev/dabo#27]
First I have been dealing with the easy stuff first:
like print to print() and except Exception,e to except Exception as e.
I decided to start with dApp and get that to work (may have been a mistake) and I am now able to run dApp without error.  There were lots of changes and I believe I have solved them.  The issue with relative path has me concerned. In the dApp.py I just used "." in front of some of the dabo specific modules and all worked (like from .dSecurityManager import dSecurityManager).  But when I started with dLabel the relative path does not work.  Do you have a suggestion? on how to fix this issue?

**Comment by EdLeafe** [comment]
Are you working with the dabo3 branch? All of that stuff should have already been dealt with. The only issues I have been having is accessing some wxPython objects causes a segfault.

**Comment by jfabiani** [comment]
I thought I was but maybe I am not since you state that it was all take care of.  I'll check further.

**Comment by jfabiani** [comment]
I don't know what I did wrong but I'm starting over.
