### ISSUE TITLE
getting error from dConnection -> getDaboCursor()

### ISSUE THREAD

**Issue by jfabiani** [dabodev/dabo#28]
At least I'm working with the right branch - dabo3.
Linux (OpenSuse 15.0), Python 3.6.5, wxPython 4.0.4
I get the following error:
Invalid keyword arguments passed to <dabo.db.dConnection.DaboCursor (baseclass dabo.db.dConnection.dConnection.getDaboCursor.<locals>.DaboCursor, id:140148928173976)>: 'connection'
from line:
crs = bo.getCursor(DaboCursor)

Johnf

**Comment by EdLeafe** [comment]
That should be a warning, not an error. It was an exception in Dabo 2, but because the latest wxPython requires full super() implementation, it is necessary to pass extra keyword args now.

**Comment by jfabiani** [comment]
I run dLabel and I get below - but you say they are warnings and a bunch of your print() statements - but nothing opens and I get Segmentation fault.  Is this what you are seeing????
output from running dLabel.py:
Invalid keyword arguments passed to <dabo.db.dConnection.DaboCursor (baseclass dabo.db.dConnection.dConnection.getDaboCursor.<locals>.DaboCursor, id:140444879456296)>: 'connection'
Invalid keyword arguments passed to <dabo.db.dConnection.DaboCursor (baseclass dabo.db.dConnection.dConnection.getDaboCursor.<locals>.DaboCursor, id:140444879456440)>: 'connection'
Invalid keyword arguments passed to <dabo.db.dConnection.DaboCursor (baseclass dabo.db.dConnection.dConnection.getDaboCursor.<locals>.DaboCursor, id:140444879456584)>: 'connection'
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:100)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <  (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dMenu.remove of <FileMenu (baseclass dabo.ui.dMenu, id:101)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:102)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Command Win&dow	Ctrl+D (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dCheckMenuItem (baseclass dabo.ui.dMenuItem, id:103)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <De&bug Output Window	Ctrl+B (baseclass dabo.ui.dMenuItem, id:-2)>>
SET AFTER <De&bug Output Window	Ctrl+B (baseclass dabo.ui.dMenuItem, id:-2)> Checked True
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dCheckMenuItem (baseclass dabo.ui.dMenuItem, id:104)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Object &Inspector	Ctrl+Shift+I (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:105)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Close Windo&w	Ctrl+W (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <dabo.ui.dMenuItem.dSeparatorMenuItem (baseclass dabo.ui.dMenuItem.dSeparatorMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:106)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&Quit	Ctrl+Q (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <FileMenu (baseclass dabo.ui.dMenu, id:107)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:109)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <  (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dMenu.remove of <EditMenu (baseclass dabo.ui.dMenu, id:110)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:111)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&Undo	Ctrl+Z (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:112)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&Redo	Ctrl+Shift+Z (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <dabo.ui.dMenuItem.dSeparatorMenuItem (baseclass dabo.ui.dMenuItem.dSeparatorMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:113)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Cu&t	Ctrl+X (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:114)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&Copy	Ctrl+C (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:115)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&Paste	Ctrl+V (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:116)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Select &All	Ctrl+A (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <dabo.ui.dMenuItem.dSeparatorMenuItem (baseclass dabo.ui.dMenuItem.dSeparatorMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:117)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&Find / Replace	Ctrl+F (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:118)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Find A&gain	Ctrl+G (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <dabo.ui.dMenuItem.dSeparatorMenuItem (baseclass dabo.ui.dMenuItem.dSeparatorMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:119)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Pr&eferences (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <EditMenu (baseclass dabo.ui.dMenu, id:120)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:122)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <  (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dMenu.remove of <ViewMenu (baseclass dabo.ui.dMenu, id:123)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:124)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Increase Font Size	Ctrl++ (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:125)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Decrease Font Size	Ctrl+- (baseclass dabo.ui.dMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:126)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Normal Font Size	Ctrl+/ (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <dabo.ui.dMenuItem.dSeparatorMenuItem (baseclass dabo.ui.dMenuItem.dSeparatorMenuItem, id:-2)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dCheckMenuItem (baseclass dabo.ui.dMenuItem, id:127)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <Show/Hide Sizer &Lines	Ctrl+L (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <ViewMenu (baseclass dabo.ui.dMenu, id:128)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:130)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <  (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dMenu.remove of <HelpMenu (baseclass dabo.ui.dMenu, id:131)>>
Invalid keyword arguments passed to <dabo.ui.dMenuItem.dMenuItem (baseclass dabo.ui.dMenuItem, id:132)>: 'kind', 'text'
CALL AFTER <bound method dPemMixin._afterInitAll of <&About Dabo Application (baseclass dabo.ui.dMenuItem, id:-2)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <HelpMenu (baseclass dabo.ui.dMenu, id:133)>>
CALL AFTER <bound method dPemMixin._afterInitAll of <dBaseMenuBar (baseclass dabo.ui.dMenuBar, id:-31993)>>

(dLabel.py:24254): Gtk-CRITICAL **: gtk_accel_groups_from_object: assertion 'G_IS_OBJECT (object)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_accel_groups_from_object: assertion 'G_IS_OBJECT (object)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_accel_groups_from_object: assertion 'G_IS_OBJECT (object)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_accel_groups_from_object: assertion 'G_IS_OBJECT (object)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(dLabel.py:24254): Gtk-CRITICAL **: gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
